# Generated by Django 5.1.1 on 2024-11-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
